-- Snowflake Table Schema for Retail Transactions
-- Run this script in your Snowflake environment to create the necessary tables

-- Create database and schema (if not exists)
CREATE DATABASE IF NOT EXISTS RETAIL_DATA;
CREATE SCHEMA IF NOT EXISTS RETAIL_DATA.ANALYTICS;

USE DATABASE RETAIL_DATA;
USE SCHEMA ANALYTICS;

-- Main transactions table
CREATE OR REPLACE TABLE RETAIL_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    QUANTITY INTEGER,
    UNIT_PRICE DECIMAL(10, 2),
    TOTAL_AMOUNT DECIMAL(10, 2),
    TRANSACTION_DATE TIMESTAMP_NTZ,
    STORE_ID VARCHAR(50),
    PAYMENT_METHOD VARCHAR(50),
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_QUALITY_SCORE DECIMAL(5, 2)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_customer ON RETAIL_TRANSACTIONS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS idx_date ON RETAIL_TRANSACTIONS(TRANSACTION_DATE);
CREATE INDEX IF NOT EXISTS idx_store ON RETAIL_TRANSACTIONS(STORE_ID);

-- Aggregated daily sales table
CREATE OR REPLACE TABLE DAILY_SALES_SUMMARY (
    SALE_DATE DATE PRIMARY KEY,
    TOTAL_TRANSACTIONS INTEGER,
    TOTAL_REVENUE DECIMAL(15, 2),
    AVERAGE_ORDER_VALUE DECIMAL(10, 2),
    UNIQUE_CUSTOMERS INTEGER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Customer dimension table
CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Product dimension table
CREATE OR REPLACE TABLE DIM_PRODUCTS (
    PRODUCT_ID VARCHAR(50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    UNIT_PRICE DECIMAL(10, 2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Data quality audit table
CREATE OR REPLACE TABLE DATA_QUALITY_AUDIT (
    AUDIT_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(100),
    ROWS_PROCESSED INTEGER,
    ROWS_PASSED INTEGER,
    ROWS_FAILED INTEGER,
    QUALITY_SCORE DECIMAL(5, 2),
    AUDIT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Grant permissions (adjust role as needed)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE SYSADMIN;

-- Verify tables created
SHOW TABLES IN SCHEMA ANALYTICS;
